# Generated by Django 4.1.6 on 2023-02-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
    ]
