# Generated by Django 4.1.6 on 2023-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0004_remove_clubrepresentative_full name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrepresentative',
            name='clubNumber',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
