# Generated by Django 4.1.6 on 2023-02-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_clubrepresentative_clubnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrepresentative',
            name='representClub',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.club'),
        ),
    ]
